### ISSUE TITLE
Can not find projectId when using exporter-auto-0.15.0-alpha.jar

### ISSUE THREAD

**Issue by kb99** [GoogleCloudPlatform/opentelemetry-operations-java#107]
docker image - `gcr.io/distroless/java-debian10:11-nonroot`

Running in k8s cluster in GCP.

This version works
`ENTRYPOINT ["java","-javaagent:/app/opentelemetry-javaagent-all-v0.11.0.jar",  "-Dotel.exporter.jar=/app/exporter-auto-0.10.1.jar", "-Dotel.propagators=tracecontext,baggage,b3multi,b3", "-Dotel.config.sampler.probability=0.001", "-jar","/app/api-0.0.1-SNAPSHOT.jar"]`

This version throws an error trying to get the `projectId`

`ENTRYPOINT ["java","-javaagent:/app/opentelemetry-javaagent-all-v1.1.0.jar", "-Dotel.javaagent.experimental.exporter.jar=/app/exporter-auto-0.15.0-alpha.jar", "-Dotel.propagators=tracecontext,baggage,b3multi,b3", "-Dotel.metrics.exporter=none",  "-jar","/app/api-0.0.1-SNAPSHOT.jar"]`

(I've also tried with `opentelemetry-javaagent-all-v1.0.1.jar` as well)

```
[opentelemetry.auto.trace 2021-05-04 13:43:02:574 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.1.0
ERROR io.opentelemetry.javaagent.OpenTelemetryAgent
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:64)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.startAgent(AgentInitializer.java:44)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:30)
	... 12 more
Caused by: java.lang.IllegalArgumentException: Cannot find a project ID from either configurations or application default.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at com.google.cloud.opentelemetry.trace.TraceConfiguration$Builder.build(TraceConfiguration.java:163)
	at com.google.cloud.opentelemetry.trace.TraceExporter.createWithDefaultConfiguration(TraceExporter.java:47)
	at com.google.cloud.opentelemetry.auto.GoogleCloudSpanExporterFactory.fromConfig(GoogleCloudSpanExporterFactory.java:34)
	at io.opentelemetry.javaagent.tooling.AgentTracerProviderConfigurer.installSpanExporter(AgentTracerProviderConfigurer.java:120)
	at io.opentelemetry.javaagent.tooling.AgentTracerProviderConfigurer.installExportersFromJar(AgentTracerProviderConfigurer.java:90)
	at io.opentelemetry.javaagent.tooling.AgentTracerProviderConfigurer.maybeConfigureExporterJar(AgentTracerProviderConfigurer.java:70)
	at io.opentelemetry.javaagent.tooling.AgentTracerProviderConfigurer.configure(AgentTracerProviderConfigurer.java:47)
	at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureTracerProvider(TracerProviderConfiguration.java:44)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:47)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installAgentTracer(OpenTelemetryInstaller.java:40)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.beforeByteBuddyAgent(OpenTelemetryInstaller.java:27)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installComponentsBeforeByteBuddy(AgentInstaller.java:174)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:92)
```

If we explicity set the `projectId` in an envionment variable in the container then the error doesn't occur.
However, we still cant see any metrics getting exported to the google dashboard.

**Comment by jsuereth** [comment]
Think I figured this out on GKE.  For some reason, the new trace client lib is looking at url "http://metadata" instead of "http://metadata.google.internal" to look up the project id.  WIll see if we can find a version where this works.

**Comment by punya** [comment]
I thought that the metadata URL was the same across GCE and GKE. What makes this fix specific to GKE?

I did see a GKE feature to block access to metadata (https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata) but that seems like a different issue - we need to tell people that auto-detection won’t work in that scenario.

**Comment by jsuereth** [comment]
They're not.  The first resolves on GCE but not GKE which is why this only manifests in GKE.

If users shut down metadata server access, then we can't do auto project id discovery, but then they should be able to configure it via environment variables (standard across our client libs).

In this case it was just a really old client library we were using that hadn't been bumped to the (more verbose) new metadata url.
