### ISSUE TITLE
Metric labels for this user-defined metric are required to be of type 'STRING'

### ISSUE THREAD

**Issue by jacekszlachtass** [GoogleCloudPlatform/opentelemetry-operations-java#159]
Hi,

Any idea what can be causing such error:

```
[otel.javaagent 2022-08-01 20:39:31:957 +0000] [PeriodicMetricReader-1] WARN com.google.cloud.opentelemetry.metric.GoogleCloudMetricExporter - Failed to create metric descriptors
com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Field labels[2].valueType had an invalid value of "INT64": Metric labels for this user-defined metric are required to be of type 'STRING': workload.googleapis.com
        at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:49)
        at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
        at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
        at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
        at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1074)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
        at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jsuereth** [comment]
This is related.  We need to use string-only metrics based on the domain in the Cloud Monitoring API.  Will need to update all exporters.

**Comment by aabmass** [comment]
Triaged again today. We think is still important enough to be fixed in the next few months as it is a bug.

The fix will be to convert the int64 to a string before sending. If you want to do this change in your instrumentation, that would also work.

**Comment by psx95** [comment]
Verified that the users would also encounter the same issue if they use Boolean keys too. 

```java
	private void recordCall(Meter meter) {
		LongCounter counter = meter
				.counterBuilder("processed_jobs")
				.setDescription("Processed jobs")
				.setUnit("LONG")
				.build();

		Attributes attributes = Attributes.of(AttributeKey.LongKey("RootLong"), 1L); // fails
                // Attributes attributes = Attributes.of(AttributeKey.booleanKey("RootBool"), true); - this would also fail
		counter.add(1, attributes);
	}
```

The following method fails
