### ISSUE TITLE
GCP automatic propagator doesn't work as per README

### ISSUE THREAD

**Issue by AkselAllas** [GoogleCloudPlatform/opentelemetry-operations-java#163]
Following this README:
<img width="999" alt="image" src="https://user-images.githubusercontent.com/26136082/193811371-073f60f4-6457-4c95-a4d3-591888911718.png">

I have the following packages as dependencies

```
  implementation("io.opentelemetry:opentelemetry-api:1.18.0")
  implementation("com.google.cloud.opentelemetry:propagators-gcp:0.23.0-alpha")
```

I have the following jvm args:
```
"-javaagent:" + project.buildDir.toString() + "/otel/opentelemetry-javaagent.jar", "-otel.propagators=gcp")
```

And as a result I got:

```
OpenTelemetry Javaagent failed to start
io.opentelemetry.sdk.autoconfigure.spi.ConfigurationException: Unrecognized value for otel.propagators: gcp. Make sure the artifact including the propagator is on the classpath.
        at io.opentelemetry.sdk.autoconfigure.PropagatorConfiguration.getPropagator(PropagatorConfiguration.java:62)
        at io.opentelemetry.sdk.autoconfigure.PropagatorConfiguration.configurePropagators(PropagatorConfiguration.java:43)
        at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:381)
        at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installOpenTelemetrySdk(OpenTelemetryInstaller.java:41)
        at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:112)
        at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:94)
        at io.opentelemetry.javaagent.tooling.AgentStarterImpl.internalStart(AgentStarterImpl.java:86)
        at io.opentelemetry.javaagent.tooling.AgentStarterImpl.start(AgentStarterImpl.java:67)
        at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:35)
        at io.opentelemetry.javaagent.OpenTelemetryAgent.startAgent(OpenTelemetryAgent.java:57)
        at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:45)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Error: Could not find or load main class .otel.propagators=gcp
Caused by: java.lang.ClassNotFoundException: /otel/propagators=gcp
```

**Comment by jsuereth** [comment]
When using the autoinstrumentation agent, you also need to pass our propagators to the autoinstrumentation "extension" classpath.

E.g. [here](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/main/examples/autoinstrument/build.gradle#L63) are the flags we set in our autoinstrumentation example container build.

Specifically `-Dotel.javaagent.experimental.extensions=otel-gcp-auto.jar` (or wherever you download it to)

**Comment by AkselAllas** [comment]
Got it working with the `-Dotel.javaagent.experimental.extensions=otel-gcp-auto.jar` flag and after using `project.buildDir.toString()` to make sure directory in docker image is correct.

But the README should include a reference to needing this flag. Before it does, I don't think this issue should be closed.

**Comment by aabmass** [comment]
Triaged, @psx95 will update the README
