### ISSUE TITLE
Javaagent still using otlp exporter after installing exporter-auto

### ISSUE THREAD

**Issue by jonshofman** [GoogleCloudPlatform/opentelemetry-operations-java#95]
Hi,

I'm trying to install the otl javaagent with exporter-auto jar on a tomcat server, currently running in a local docker image.

When starting the server, the log seem to point out the Google trace and Metrics exporters are installed correctly, however when exporting metrics and spans, still a connection is made using the default OTLP exporter.

I've added the the agent and exporter jar's to the CATALINA_OPTS:

```
CATALINA_OPTS="$CATALINA_OPTS -Dotel.exporter.jar=/usr/local/tomcat/lib/exporter-auto-0.11.0.jar"
CATALINA_OPTS="$CATALINA_OPTS -javaagent:/usr/local/tomcat/lib/opentelemetry-javaagent-0.18.0-SNAPSHOT-all.jar"
```

On server statup I see the following in the stdout.log, I think implying that the agent and exporter are installed correctly:

```
[opentelemetry.auto.trace 2021-03-04 13:46:05:100 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 0.18.0-SNAPSHOT

[opentelemetry.auto.trace 2021-03-04 13:46:10:371 +0000] [main] INFO io.opentelemetry.javaagent.tooling.AgentTracerProviderConfigurer - Installed span exporter: com.google.cloud.opentelemetry.trace.TraceExporter

[opentelemetry.auto.trace 2021-03-04 13:46:10:689 +0000] [main] INFO io.opentelemetry.javaagent.tooling.AgentTracerProviderConfigurer - Installed metric exporter: com.google.cloud.opentelemetry.metric.MetricExporter

```
But later on I see the following error, failing on the default otlp exporter:

```
[IntervalMetricReader-1] WARN io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporter - Failed to export metrics

io.grpc.StatusRuntimeException: UNAVAILABLE: io exception

at io.grpc.Status.asRuntimeException(Status.java:534)

at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)

at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)

at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)

at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)

at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)

at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)

at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)

at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

at java.base/java.lang.Thread.run(Thread.java:834)

Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:4317

Caused by: java.net.ConnectException: Connection refused

at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)

at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)

at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)

at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)

at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)

at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)

at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)

at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)

at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)

at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

at java.base/java.lang.Thread.run(Thread.java:834)
```

Any pointers on how to solve this would be highly appreciated.

Thanks.

**Comment by jsuereth** [comment]
Two things:

1. OTel just reworked autoconfiguration a bit in the latest snapshot.  Does it work on 0.17?
2. Our released auto agent is pretty stale.  You could try to build from head (where we are up-to-date against 0.17) and see if that resolves the problem.  It's possible class loading incompatible issues are being supressed so our exporter is dropped.

I won't have time to look into details (sorry), but I plan to issue a release against 1.0 API shortly (monday) that should help.  In the meantime, feel free to build the jar locally and see if that helps!

**Comment by jonshofman** [comment]
Hi Josh,

Sorry for the late reply, yes I've also tried different versions of the agent and the exporter.

Also enabled the debug flag, and came across this error there that looks like the root cause. 

Not really sure whether it's related to the exporter, or some mis-configuration in my docker image.

```
[opentelemetry.auto.trace 2021-03-10 10:28:11:655 +0000] [main] DEBUG io.grpc.ManagedChannelRegistry - Unable to find OkHttpChannelProvider

java.lang.ClassNotFoundException: io.grpc.okhttp.OkHttpChannelProvider

at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)

at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)

at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

at java.base/java.lang.Class.forName0(Native Method)

at java.base/java.lang.Class.forName(Class.java:315)

at io.grpc.ManagedChannelRegistry.getHardCodedClasses(ManagedChannelRegistry.java:134)

at io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:98)

at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:41)

at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)

at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:280)

at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1600(InstantiatingGrpcChannelProvider.java:71)

at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:210)

at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)

at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:217)

at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:200)

at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:166)

at com.google.cloud.trace.v2.stub.GrpcTraceServiceStub.create(GrpcTraceServiceStub.java:73)

at com.google.cloud.trace.v2.stub.TraceServiceStubSettings.createStub(TraceServiceStubSettings.java:104)

at com.google.cloud.trace.v2.TraceServiceClient.<init>(TraceServiceClient.java:137)

at com.google.cloud.trace.v2.TraceServiceClient.create(TraceServiceClient.java:118)

at com.google.cloud.opentelemetry.trace.TraceExporter.createWithCredentials(TraceExporter.java:94)

at com.google.cloud.opentelemetry.trace.TraceExporter.createWithConfiguration(TraceExporter.java:62)

at com.google.cloud.opentelemetry.trace.TraceExporter.createWithDefaultConfiguration(TraceExporter.java:48)

at com.google.cloud.opentelemetry.auto.GoogleCloudSpanExporterFactory.fromConfig(GoogleCloudSpanExporterFactory.java:34)

at io.opentelemetry.javaagent.tooling.AgentTracerProviderConfigurer.installSpanExporter(AgentTracerProviderConfigurer.java:123)

at io.opentelemetry.javaagent.tooling.AgentTracerProviderConfigurer.installExportersFromJar(AgentTracerProviderConfigurer.java:91)

at io.opentelemetry.javaagent.tooling.AgentTracerProviderConfigurer.maybeConfigureExporterJar(AgentTracerProviderConfigurer.java:71)

at io.opentelemetry.javaagent.tooling.AgentTracerProviderConfigurer.configure(AgentTracerProviderConfigurer.java:48)

at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureTracerProvider(TracerProviderConfiguration.java:40)

at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:45)

at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installAgentTracer(OpenTelemetryInstaller.java:36)

at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.beforeByteBuddyAgent(OpenTelemetryInstaller.java:27)

at io.opentelemetry.javaagent.tooling.AgentInstaller.installComponentsBeforeByteBuddy(AgentInstaller.java:169)

at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:103)

at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:87)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/java.lang.reflect.Method.invoke(Method.java:566)

at io.opentelemetry.javaagent.bootstrap.AgentInitializer.startAgent(AgentInitializer.java:44)

at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:30)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/java.lang.reflect.Method.invoke(Method.java:566)

at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:64)

at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:51)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/java.lang.reflect.Method.invoke(Method.java:566)

at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)

at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
```

**Comment by bokjo** [comment]
> Two things:
> 
> 1. OTel just reworked autoconfiguration a bit in the latest snapshot.  Does it work on 0.17?
> 2. Our released auto agent is pretty stale.  You could try to build from head (where we are up-to-date against 0.17) and see if that resolves the problem.  It's possible class loading incompatible issues are being supressed so our exporter is dropped.
> 
> I won't have time to look into details (sorry), but I plan to issue a release against 1.0 API shortly (monday) that should help. In the meantime, feel free to build the jar locally and see if that helps!

Hello @jsuereth,

Thanks for the reply, I'm on the same team with @jonshofman and we have managed to make [v0.14.0-RC1 ](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/releases/tag/v0.14.0-RC1) work with Otel v0.15.0 and Otel-instrumentation v0.15.0 as well... even tho the Gradle build config says it is built with 0.14.0 respectively (I guess the Otel API had no braking changes between 0.14.0 and 0.15.0...)

Also, I build from master HEAD with the latest changes to otel-v1.0.0 and otel-instrumentation-v0.17.0 and works only with `opentelemetry-javaagent-0.17.0-all.jar` (instrumentation-java-0.17.0).

https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/c60054608b3bced0885e26359b97ef6cca290ad4/build.gradle#L110
```
openTelemetryVersion = '1.0.0'
openTelemetryInstrumentationVersion = '0.17.0'
```

I have noticed that this build relies on JFrog for the java artifacts... and there the latest one is [v0.17.0-alpha](https://oss.jfrog.org/artifactory/webapp/#/search/quick/eyJzZWFyY2giOiJxdWljayIsInF1ZXJ5Ijoib3BlbnRlbGVtZXRyeS1qYXZhYWdlbnQtc3BpLTAuMTcuMCJ9) for the `opentelemetry-java-instrumentation`.

So my question is who is responsible for pushing the Java artifacts to JFrog (i guess opentelemety-java project..) and when can we expect v1.0.x on JFrog in order to be able to build (and possibly for you to release v1) this project with the latest Otel now stable v1 version I guess.

On a side note [Maven Central](https://search.maven.org/artifact/io.opentelemetry.javaagent/opentelemetry-javaagent-spi) already has the otel-v1.0.x-alpha and otel-java-instrumentaion-v1.0.x-alpha.

I'm not a Java developer per se, but please let us know if we can help in any shape or form :)

Kind Regards,
Bojanche S.

**Comment by jsuereth** [comment]
Hey @bokjo 

Two things:

1. JFrog turned down bintray, so likely we won't see an update there.
2. I bumped our major version to 1.0.1.  It looks like you ran into a classloader issue for mismatched versions.  I need to patch some upstream changes to auto-instrumentation in OTel to prevent that issue going forward (i.e. we want more flexibility in versioning between the OTel agent and our auto-exporter plugin.


Our `0.14.0-alpha` version should be on maven central now and *is* compatible with Java instrumentation 0.17.0-alpha of OTEL Instrumentation.  I can cut a `0.15.0-alpha` against the `1.0.1-alpha` of Java instrumentation if you need it, let me know.

**Comment by jsuereth** [comment]
> Hi Josh,
> 
> Sorry for the late reply, yes I've also tried different versions of the agent and the exporter.
> 
> Also enabled the debug flag, and came across this error there that looks like the root cause.
> 
> Not really sure whether it's related to the exporter, or some mis-configuration in my docker image.

This looks like a classloader issue with gRPC versions and visibility.  I had a proposal from a while ago to fix this. I think we need to do two things:

1. We should "shade " our usage of gRPC locally appropriately.  I need to check this reflective usage gets appropraitely shaded.
2. I have a proposal to re-architect the Java instrumentation agent's exporter-loading feature to better isolate classloaders and avoid version-skew problems like this.  That'll take some time though.

**Comment by bokjo** [comment]
> Hey @bokjo
> 
> Two things:
> 
> 1. JFrog turned down bintray, so likely we won't see an update there.
> 2. I bumped our major version to 1.0.1.  It looks like you ran into a classloader issue for mismatched versions.  I need to patch some upstream changes to auto-instrumentation in OTel to prevent that issue going forward (i.e. we want more flexibility in versioning between the OTel agent and our auto-exporter plugin.
> 
> Our `0.14.0-alpha` version should be on maven central now and _is_ compatible with Java instrumentation 0.17.0-alpha of OTEL Instrumentation. I can cut a `0.15.0-alpha` against the `1.0.1-alpha` of Java instrumentation if you need it, let me know.

Hello @jsuereth,

Thanks for the reply, hopefully, today or tomorrow I will test with the new auto-exporter 0.14.0 with Otel v1.0 and see how it goes. ( I can always build against 0.17.0 as well since we are still not on production!) 

We made a bit of change on our [custom instrumentation](https://github.com/jonshofman/opentelemetry-java-instrumentation/tree/v0.17.0-with-lucee-instrumentation/instrumentation/lucee/javaagent) and derived it from java-instrumentation 0.17.0 so moving it to v1.0.1 shouldn't be a problem, or rather work out of the box. Once it is completed and more future rich we will align it with the latest OTel and release it! It just has to work with GCP for us first :)

If there is any problem I'll let you know.

Cheers and happy week.

Kind Regards,
Bojanche S.

**Comment by jsuereth** [comment]
I'm going to mark this as closed for now.  We recently bumped another major version of the exporter (0.15.0).   Feel free to reopen if you see issues.
